name = "solball"
main = "server/index.ts"
compatibility_date = "2024-11-01"

[durable_objects]
bindings = [{ name = "GameRoom", class_name = "GameRoom" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
